# Site settings
title: Elizabeth Malara
email: elathepainter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Gallery of Ontario artist Elizabeth Malara.
  Presenting nature-inspired oil, acrylic, watercolor paintings and sketches.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://malara.ca" # the base hostname & protocol for your site
twitter_username: elamalara
github_username:  elamalara

# Build settings
markdown: kramdown
